### ISSUE TITLE
请求网络数据异常

### ISSUE THREAD

**Issue by zhuyonghao134123** [youxinLu/mall#9]
flutter: X-Litemall-Token=null
flutter: ========================请求错误===================
flutter: message =Bad state: Insecure HTTP is not allowed by platform: http://120.25.226.11:8080/mall-app/wx/auth/login
flutter: DioError [DioErrorType.DEFAULT]: Bad state: Insecure HTTP is not allowed by platform: http://120.25.226.11:8080/mall-app/wx/auth/login
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2435:7)
#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2342:7)
#2      DefaultHttpClientAdapter.fetch (package:dio/src/adapters/io_adapter.dart:35:40)
#3      DioMixin._dispatchRequest (package:dio/src/dio.dart:919:46)
<asynchronous suspension>
#4      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
#5      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1117:22)
#6      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
#7      new Future.<anonymous closure> (dart:async/future.dart:175:37)
#8      _rootRun (dart:async/zone.dart:1182:47)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.runGuarded (dart:async/zone.dar<…>
flutter: 请求网络数据异常

**Comment by youxinLu** [comment]
这个是因为手机平台对网络做了一些限制，可以参考https://blog.csdn.net/weixin_44137575/article/details/109045633先进行修复。

**Comment by youxinLu** [comment]
这个是因为手机平台对网络做了一些限制，可以参考https://blog.csdn.net/weixin_44137575/article/details/109045633先进行修复。
